name: .NET Core Desktop

on:
  push:
    branches: 
      - "main"
  pull_request:
    branches: 
      - "main"

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Set up .NET SDK
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Setup MSBuild for building desktop applications
      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v2

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build the project with the specified configuration (Debug/Release)
      - name: Build project
        run: dotnet build --configuration ${{ matrix.configuration }}

      # Run unit tests
      - name: Run tests
        run: dotnet test --configuration ${{ matrix.configuration }} --no-build --verbosity normal
