name: Build and Release DamnScript

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    name: Build and Test
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore DamnScript.sln

      - name: Build Debug
        run: dotnet build DamnScript.sln --configuration Debug --no-restore

      - name: Build Release
        run: dotnet build DamnScript.sln --configuration Release --no-restore

      - name: Run build_releases.py
        run:
          python3 Scripts/build_releases.py

      - name: List archives in Releases directory
        run: Get-ChildItem -Path "${{ github.workspace }}\\Scripts\\Releases" -Filter "DamnScript_*.zip" | Select-Object Name
        shell: pwsh

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            ${{ github.workspace }}\\Scripts\\Releases\\DamnScript_Unity_Source_Debug.zip
            ${{ github.workspace }}\\Scripts\\Releases\\DamnScript_Unity_Source_Release.zip
            ${{ github.workspace }}\\Scripts\\Releases\\DamnScript_NET_Binaries_Debug.zip
            ${{ github.workspace }}\\Scripts\\Releases\\DamnScript_NET_Binaries_Release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}